baseURL = 'https://dragon.gal/'
languageCode = 'en-us'
title = 'kryst4line'
theme = 'hugo-theme-console'
publishDir = "dist"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast"

  custom_css = ["css/style.css"]
  favicon = ["favicon.png"]

[[params.navlinks]]
  name = "about/"
  url = "about/"

[[params.navlinks]]
  name = "links/"
  url = "links/"

[[params.navlinks]]
  name = "projects/"
  url = "projects/"

[[params.navlinks]]
  name = "music/"
  url = "music/"
